[data-path]

# both full_corpus and works_subset lives inside data_path

upstream-path = "data/parquet"
data-path = "/data/scholar_rank/data"          # Storing compacted shards after extraction
posting-path = "/data/scholar_rank/posting"              # Store posting data
tmp-corpus-folder = "tmp"
full-corpus-folder = "full_corpus"
works-subset-folder = "works_subset"

[works-subset.subset-profiles]
"math-en" = "topics[1].field_display_name = 'Mathematics' AND language = 'en'"
"engr-en" = "topics[1].field_display_name = 'Engineering' AND language = 'en'"
"vet-en" = "topics[1].field_display_name = 'Veterinary' AND language = 'en'"